<a href="https://colab.research.google.com/github/tsuli/hands-on-time-series-analylsis-python/blob/master/keras_ch3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf
x = tf.ones(shape = (2, 1))
print(x)


tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)


In [5]:
x = tf.zeros(shape = (2, 1))
print(x)

tf.Tensor(
[[0.]
 [0.]], shape=(2, 1), dtype=float32)


In [6]:
x = tf.random.normal(shape=(3, 1), mean = 0., stddev=1)
print(x)

tf.Tensor(
[[ 1.952903 ]
 [ 0.5038965]
 [-2.4381564]], shape=(3, 1), dtype=float32)


In [7]:
tf.random.uniform(shape = (3, 1), minval = 0., maxval = 1.)
print(x)

tf.Tensor(
[[ 1.952903 ]
 [ 0.5038965]
 [-2.4381564]], shape=(3, 1), dtype=float32)


In [9]:
import numpy as np
x = np.ones(shape=(2, 2))
x[0, 0] = 0.

In [10]:
x = tf.ones(shape=(2, 2))
x[0, 0] = 0.

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [11]:
v = tf.Variable(initial_value = tf.random.normal(shape = (3, 1)))
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[-0.27394304],
       [-1.6450642 ],
       [-0.8010677 ]], dtype=float32)>


In [13]:
v.assign(tf.ones((3, 1)))

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>